# Window Customization
window:
  dimensions:
    columns: 140
    lines: 38
  padding:
    x: 25
    y: 25
  decorations: none
scrolling:
  history: 10000
  multiplier: 3
background_opacity: 1
window.dynamic_title: true

# Font Customization
font:
  normal:
    family: Fira Code
    style: Regular
  bold:
    family: Fira Code
    style: Bold
  italic:
    family: Fira Code
    style: Italic
  size: 14
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
  use_thin_strokes: false
  debug:
    persistent_logging: false
draw_bold_text_with_bright_colors: true

# Colros (Base 16 Default Dark)
colors:
  # Default colors
  primary:
    background: '0x22212c'
    foreground: '0xf8f8f2'

  # Normal colors
  normal:
    black:   '0x22212c'
    red:     '0xff9580'
    green:   '0x8aff80'
    yellow:  '0xffff80'
    blue:    '0x9580ff'
    magenta: '0xff80bf'
    cyan:    '0x80ffea'
    white:   '0xf8f8f2'

  # Bright colors
  bright:
    black:   '0x22212c'
    red:     '0xffaa99'
    green:   '0xa2ff99'
    yellow:  '0xffff99'
    blue:    '0xaa99ff'
    magenta: '0xff99cc'
    cyan:    '0x99ffee'
    white:   '0xffffff'

  indexed_colors:
    - { index: 16, color: '0xdc9656' }
    - { index: 17, color: '0xa16946' }
    - { index: 18, color: '0x282828' }
    - { index: 19, color: '0x383838' }
    - { index: 20, color: '0xb8b8b8' }
    - { index: 21, color: '0xe8e8e8' }

  selection:
    text: '0xf8f8f2'
    background: '0x415854'

cursor:
  style: Block
  unfocused_hollow: true

#key_bindings:
#  - { key: N, mods: Control, action: SpawnNewInstance }
